repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
        exclude: ^docs/
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    - id: isort
